/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "background": "#000000",
        "surface": "#0a0515",
        "surface-dim": "#0a0515",
        "surface-bright": "#1b1133",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#0a0515",
        "surface-container": "#0a0515",
        "surface-container-high": "#120b22",
        "surface-container-highest": "#1c1133",
        "surface-variant": "#0a0515",
        "on-surface": "#FFFFFF",
        "on-surface-variant": "#e2e2e2",
        "on-background": "#FFFFFF",
        "inverse-surface": "#FFFFFF",
        "inverse-on-surface": "#000000",
        "outline": "#8342fb",
        "outline-variant": "#1c1133",
        "surface-tint": "#FFFFFF",
        "primary": "#FFFFFF",
        "on-primary": "#000000",
        "primary-container": "#0a0515",
        "on-primary-container": "#FFFFFF",
        "inverse-primary": "#e2e2e2",
        "primary-fixed": "#FFFFFF",
        "primary-fixed-dim": "#e2e2e2",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#e2e2e2",
        "secondary": "#A0D600",
        "on-secondary": "#000000",
        "secondary-container": "#A0D600",
        "on-secondary-container": "#000000",
        "secondary-fixed": "#A0D600",
        "secondary-fixed-dim": "#A0D600",
        "on-secondary-fixed": "#000000",
        "on-secondary-fixed-variant": "#000000",
        "tertiary": "#8342fb",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#0a0515",
        "on-tertiary-container": "#ffffff",
        "tertiary-fixed": "#8342fb",
        "tertiary-fixed-dim": "#8342fb",
        "on-tertiary-fixed": "#ffffff",
        "on-tertiary-fixed-variant": "#8342fb",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      spacing: {
        "unit": "8px",
        "gutter": "32px",
        "margin-mobile": "24px",
        "margin-desktop": "80px",
        "section-gap": "160px",
      },
      fontFamily: {
        "display-xl": ["Poppins", "sans-serif"],
        "headline-lg": ["Poppins", "sans-serif"],
        "headline-lg-mobile": ["Poppins", "sans-serif"],
        "subheading": ["Poppins", "sans-serif"],
        "body-md": ["Poppins", "sans-serif"],
        "label-caps": ["Poppins", "sans-serif"],
        "sans": ["Poppins", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "subheading": ["20px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        full: "9999px",
      },
      maxWidth: {
        "7xl": "80rem",
      },
      backgroundImage: {
        "glow-lime": "radial-gradient(circle at center, rgba(160, 214, 0, 0.08) 0%, transparent 70%)",
        "glow-purple": "radial-gradient(circle at center, rgba(131, 66, 251, 0.08) 0%, transparent 70%)",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        float: "float 8s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
